version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do contêiner para a porta 3000 do host
    environment:
      - DB_HOST=db  # Define o nome do serviço do PostgreSQL como 'db'
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=meubanco
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do contêiner para o host

volumes:
  postgres_data:


version: '3'
services:
  app:
    image: node:14
    container_name: app-container
    networks:
      - my_network
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    networks:
      - my_network
    ports:
      - "5432:5432"
networks:
  my_network:
    driver: bridge

 
